let ramNames = [
    "J Adams",
    "Md Al Amin",
    "S Al-Qurashi",
    "A Ammar",
    "E BeAney",
    "P Bennabhaktula",
    "D Butkus",
    "C Callahan",
    "C Campbell",
    "L Capasso",
    "T Cavey",
    "D Chavez",
    "C Coleman",
    "D Cooke",
    "J Cuillard",
    "D Cupit",
    "N Czarnecki",
    "K Dassler",
    "O Davidson",
    "M DeBlois",
    "C Dobiash",
    "T Donsereaux",
    "A E Boroojeny",
    "J Eschen",
    "P Fairburn",
    "D Ferrer",
    "Z Garno",
    "J Ghosh",
    "G Gilbert",
    "J Ham",
    "Tianzhao He",
    "M Heil",
    "S Hiray",
    "K Hobbs",
    "B Hua",
    "S Hultin",
    "L Johnson",
    "B Jungen",
    "T Kancharla",
    "N Kaufhold",
    "P Keleher",
    "C Key",
    "A Kumar",
    "K Lagerberg",
    "E Lavertu",
    "P Lee",
    "T Magee",
    "A Marquez",
    "D Meiklejohn",
    "W Musser",
    "G Nard",
    "S Nardos",
    "A Neubauer",
    "W Nichols",
    "N ODell",
    "D Padalia",
    "U Paudel",
    "R Peck",
    "R Petrovec",
    "E Pike",
    "B Reutimann",
    "D Rhoades",
    "M Ridgeway",
    "L Rone",
    "M Rosoff",
    "T Schultz",
    "C Seewald",
    "V Shastri",
    "M Singh",
    "K Skunberg",
    "A Smelianski",
    "A Soto",
    "H Sullivan",
    "A Tate",
    "A Thompson",
    "J Topps",
    "M Vera",
    "A Watts",
    "P Weaver",
    "A Whitehouse",
    "F Worm",
    "A Ykalo",

    "Bellatrix",
    "Netherspike",
    "Lizard",
    "Leander",
    "Phaser",
    "Falazure",
    "Brokenfang",
    "Raisin",
    "Hecate",
    "Harry",
    "Snape",
    "Miasma",
    "Shimmer",
    "Grassclaw",
    "MrCuddles",
    "Ambiance",
    "Chupathingy",
    "DoubleVision",
    "Acheron",
    "CaptainSmile",
    "Chimichanga",
    "Fume",
    "Loki",
    "Feathermoon",
    "Absinthe",
    "Nereus",
    "Cyanide",
    "Ellegon",
    "Slicer",
    "Spyro",
    "DoubleTrouble",
    "Zipactonal",
    "TipTap",
    "Grassclaw",
    "Snuggles",
    "IllBiteU",
    "Ancalagon",
    "Elpis",
    "Feathermoon",
    "Carboniferous",
    "Bloodmaw",
    "Namacuix",
    "Drakoth",
    "Dementionisa",
    "Aura",
    "Knuckle",
    "MagicShroom",
    "Mothball",
    "Polyporus",
    "GlowStick",
    "Zothogth",
    "Luminati",
    "ShotSathothu",
    "Russula",
    "SeanOfTheDead",
    "Tigger",
    "Hugs",
    "Blink",
    "Gemini",
    "Viral",
    "Ambiance",
    "Severjaw",
    "Ripmaw",
    "Cthulhu",
    "Herakles",
    "Orestes",
    "Astilabor",
    "Toltecatl",
    "Blinky",
    "Adrasteia",
    "Fleck",
    "Arsenic",
    "Sunshine",
    "Seaspray",
    "Rishul",
    "Skitz",
    "Runzel",
    "Adonis",
    "Gelure",
    "Kahaera",
    "Teicuih",
    "BettyBoop",
    "Aura",
    "Monarch",
    "Dawn",
    "Floater",
    "Nana",
    "Arngrimr",
    "Flopsy",
    "Wiggles",
    "Predator",
    "OmNomNom",
    "Lizardbreath",
    "Gelure",
    "Aasterinian",
    "Brokenfang",
    "Cambrian",
    "Glaucus",
    "Peekaboo",
    "Ricochet",
    "Popeye",
    "Claw",
    "Mutalisk",
    "Jumeaux",
    "Silurian",
    "Smaug",
    "PrplPeplEter",
    "Deimos",
    "Flash",
    "Runningsoul",
    /*"Scotty",
   "Vanish",
   "Quickfang",
   "Manitou",
   "Chubaka",
   "Powderpuffer",
   "Pickle",
   "Flygon",
   "Jasmine",
   "ShadowDancer", */
    "Grumpy",
    "Happy",
    "Sleepy",
    "Dopey",
    "Doc",
    "Bashful",
    "Sneezy",
    "Kirk",
    "Spock",
    "McCoy",
    "Scotty",
    "Uhuru"


];

export default ramNames;